import type { Post, PostImage, Testimonial } from "@prisma/client"

const IMG = {
  plumbing1: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&auto=format&fit=crop&q=70",
  plumbing2: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&auto=format&fit=crop&q=70",
  paint1: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&auto=format&fit=crop&q=70",
  paint2: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1200&auto=format&fit=crop&q=70",
  reno1: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=70",
  reno2: "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=1200&auto=format&fit=crop&q=70",
  electric1: "https://images.unsplash.com/photo-1621905251918-48416b573323?w=1200&auto=format&fit=crop&q=70",
  electric2: "https://images.unsplash.com/photo-1581092446327-9b52bd1570c2?w=1200&auto=format&fit=crop&q=70",
  interior1: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&auto=format&fit=crop&q=70",
  kitchen: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&auto=format&fit=crop&q=70",
  bath: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&auto=format&fit=crop&q=70",
  living: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&auto=format&fit=crop&q=70",
  bedroom: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&auto=format&fit=crop&q=70",
} as const

const now = new Date()

export const FALLBACK_POSTS: (Post & { images: PostImage[] })[] = [
  {
    id: "fallback-post-1",
    title: "HDB Toilet Re-piping in Bedok",
    slug: "hdb-toilet-repiping-bedok",
    excerpt: "Replaced corroded galvanised pipes with PPR, fixed a stubborn leak under the sink.",
    content: "## The Job\n\nReplaced corroded piping with high-grade PPR heat-fused joints. Zero drop on 30-minute pressure test.",
    type: "portfolio",
    category: "Plumbing",
    tags: "HDB,Toilet,Leak",
    featured: true,
    published: true,
    coverImage: IMG.plumbing1,
    views: 142,
    whatsappClicks: 28,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-1a", postId: "fallback-post-1", url: IMG.plumbing2, kind: "before", position: 0, createdAt: now },
      { id: "img-1b", postId: "fallback-post-1", url: IMG.plumbing1, kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-2",
    title: "Full 5-Room HDB Painting in Punggol",
    slug: "painting-punggol-5room",
    excerpt: "Nippon Paint 3-in-1 medallion, ceilings included. Dust-free prep, completed in 2.5 days.",
    content: "## Process\n\nFull furniture masking, hairline crack patching, 2 coats premium Nippon Paint.",
    type: "portfolio",
    category: "Painting",
    tags: "HDB,Punggol,Nippon",
    featured: true,
    published: true,
    coverImage: IMG.paint1,
    views: 189,
    whatsappClicks: 35,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-2a", postId: "fallback-post-2", url: IMG.paint2, kind: "before", position: 0, createdAt: now },
      { id: "img-2b", postId: "fallback-post-2", url: IMG.paint1, kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-3",
    title: "Condo Kitchen Renovation in Serangoon",
    slug: "condo-kitchen-serangoon",
    excerpt: "Custom solid-surface countertop, new backsplash, full re-tiling. Two-week turnaround.",
    content: "## Execution\n\nSeamless solid surface, marine-ply carcasses with soft-close Blum hinges, herringbone marble-look tile backsplash.",
    type: "portfolio",
    category: "Renovation",
    tags: "Condo,Kitchen,Carpentry",
    featured: true,
    published: true,
    coverImage: IMG.kitchen,
    views: 210,
    whatsappClicks: 42,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-3a", postId: "fallback-post-3", url: IMG.reno1, kind: "before", position: 0, createdAt: now },
      { id: "img-3b", postId: "fallback-post-3", url: IMG.kitchen, kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-4",
    title: "Full Electrical Rewiring, Landed in Bukit Timah",
    slug: "rewiring-landed-bukit-timah",
    excerpt: "4-storey landed house, complete rewire with new distribution board. EMA-compliant, LEW-signed off.",
    content: "## Scope\n\nNew PVC conduits throughout 4 storeys, new Hager 100A DB, RCBO protection on every circuit.",
    type: "portfolio",
    category: "Electrical",
    tags: "Landed,Rewiring,LEW",
    featured: false,
    published: true,
    coverImage: IMG.electric1,
    views: 115,
    whatsappClicks: 19,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-4a", postId: "fallback-post-4", url: IMG.electric2, kind: "after", position: 0, createdAt: now },
      { id: "img-4b", postId: "fallback-post-4", url: IMG.electric1, kind: "gallery", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-5",
    title: "Master Bathroom Hack, EC in Sembawang",
    slug: "bathroom-hack-sembawang",
    excerpt: "Hacked and re-tiled a tired master bathroom. Walk-in rain shower, frameless glass.",
    content: "## Scope\n\nHacked tiles, 2 coats Sika waterproofing, large-format 600x600 marble-look tiles, walk-in rain shower.",
    type: "portfolio",
    category: "Renovation",
    tags: "Bathroom,Hack,Waterproofing",
    featured: false,
    published: true,
    coverImage: IMG.bath,
    views: 167,
    whatsappClicks: 31,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-5a", postId: "fallback-post-5", url: IMG.reno2, kind: "before", position: 0, createdAt: now },
      { id: "img-5b", postId: "fallback-post-5", url: IMG.bath, kind: "after", position: 1, createdAt: now },
    ],
  },
]

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "fallback-test-1",
    name: "Mrs Tan",
    role: "5-Room HDB Owner · Punggol",
    rating: 5,
    content: "Painted our entire flat in 2.5 days. Edges were crisp, zero paint on our furniture, and he cleaned up thoroughly before leaving. Felt like a brand new flat.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-2",
    name: "Daniel Lim",
    role: "Condo Owner · Serangoon",
    rating: 5,
    content: "Re-did my kitchen. Quote was 100% transparent, no surprises, finished on the exact date promised. The solid-surface countertop seaming was invisible.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-3",
    name: "Priya K",
    role: "BTO Owner · Sengkang",
    rating: 5,
    content: "Built my feature wall and TV console. Came back twice to fine-tune the LED lighting until I was happy. That level of after-service is rare in Singapore.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-4",
    name: "Mr Goh",
    role: "Landed Owner · Bukit Timah",
    rating: 5,
    content: "Full rewire of a 4-storey house. LEW-signed, EMA-compliant, zero snags at handover. Highly recommended trade specialist.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-5",
    name: "Aisha Bte Rahmat",
    role: "EC Owner · Sembawang",
    rating: 5,
    content: "Re-did my master bathroom. He explained the waterproofing process so I understood why it mattered. The walk-in rain shower is incredible.",
    avatar: null,
    published: true,
    createdAt: now,
  },
]
