import type { Post, PostImage, Testimonial } from "@prisma/client"

const IMG = {
  plumbing1: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&auto=format&fit=crop&q=70",
  plumbing2: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&auto=format&fit=crop&q=70",
  paint1: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&auto=format&fit=crop&q=70",
  paint2: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1200&auto=format&fit=crop&q=70",
  reno1: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=70",
  reno2: "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=1200&auto=format&fit=crop&q=70",
  electric1: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=70",
  electric2: "https://images.unsplash.com/photo-1581092446327-9b52bd1570c2?w=1200&auto=format&fit=crop&q=70",
  interior1: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&auto=format&fit=crop&q=70",
  kitchen: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&auto=format&fit=crop&q=70",
  bath: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&auto=format&fit=crop&q=70",
  living: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&auto=format&fit=crop&q=70",
  bedroom: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&auto=format&fit=crop&q=70",
} as const

const now = new Date()

export const FALLBACK_POSTS: (Post & { images: PostImage[] })[] = [
  {
    id: "fallback-post-1",
    title: "HDB Toilet Re-piping & Leak Sealing",
    slug: "hdb-toilet-repiping-leak-bedok",
    excerpt: "Replaced corroded galvanised pipes with PPR, fixed a stubborn toilet leak under the sink.",
    content: "## The Job\n\nReplaced corroded piping with high-grade PPR heat-fused joints. Zero drop on 30-minute pressure test. Completely solved persistent toilet leak.",
    type: "portfolio",
    category: "Plumbing Services",
    tags: "Toilet leaking repair,HDB,Bedok",
    featured: true,
    published: true,
    coverImage: "https://files.catbox.moe/dmagw6.png",
    views: 142,
    whatsappClicks: 28,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-1a", postId: "fallback-post-1", url: "https://files.catbox.moe/dmagw6.png", kind: "gallery", position: 0, createdAt: now },
    ],
  },
  {
    id: "fallback-post-2",
    title: "Full 5-Room HDB House Painting in Punggol",
    slug: "painting-punggol-5room",
    excerpt: "Nippon Paint 3-in-1 medallion, ceilings included. Dust-free prep, completed in 2.5 days.",
    content: "## Process\n\nFull furniture masking, hairline crack patching, 2 coats premium Nippon Paint. Crisp corners and zero paint spatter.",
    type: "portfolio",
    category: "Painting Services",
    tags: "House painting,Painting,Nippon",
    featured: true,
    published: true,
    coverImage: "https://files.catbox.moe/6pj5rs.jpg",
    views: 189,
    whatsappClicks: 35,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-2a", postId: "fallback-post-2", url: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1200&auto=format&fit=crop&q=70", kind: "before", position: 0, createdAt: now },
      { id: "img-2b", postId: "fallback-post-2", url: "https://files.catbox.moe/6pj5rs.jpg", kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-3",
    title: "Roof Leak Repair & Waterproofing in Bukit Timah",
    slug: "roof-leak-waterproofing-bukit-timah",
    excerpt: "Emergency roof leak detection, ridge capping re-sealing, and multi-layer waterproofing membrane.",
    content: "## Scope\n\nDetected hidden seepage along ridge tiles. Stripped damaged mortar, laid breathable waterproofing membrane, and realigned clay tiles with 100% watertight seal.",
    type: "portfolio",
    category: "Roofing & Waterproofing",
    tags: "Roof leaking repair,Water proofing,Bukit Timah",
    featured: true,
    published: true,
    coverImage: "https://files.catbox.moe/g2969p.jpg",
    views: 210,
    whatsappClicks: 42,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-3a", postId: "fallback-post-3", url: "https://files.catbox.moe/fcb1g7.jpg", kind: "before", position: 0, createdAt: now },
      { id: "img-3b", postId: "fallback-post-3", url: "https://files.catbox.moe/g2969p.jpg", kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-4",
    title: "Canopy Repair & Roof Tiles Realignment",
    slug: "canopy-repair-roof-tiles-landed",
    excerpt: "Restored damaged outdoor canopy frame and replaced fractured concrete roof tiles.",
    content: "## Execution\n\nReinforced outdoor canopy brackets, resealed polycarbonate sheets against heavy rain, and installed replacement roof tiles.",
    type: "portfolio",
    category: "Roofing & Waterproofing",
    tags: "Canopy repairing,Roof tiles installation",
    featured: false,
    published: true,
    coverImage: "https://files.catbox.moe/xx0tqh.jpg",
    views: 115,
    whatsappClicks: 19,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-4a", postId: "fallback-post-4", url: "https://files.catbox.moe/xx0tqh.jpg", kind: "gallery", position: 0, createdAt: now },
      { id: "img-4b", postId: "fallback-post-4", url: "https://files.catbox.moe/g2969p.jpg", kind: "gallery", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-5",
    title: "Commercial Office & Epoxy Floor Painting",
    slug: "commercial-office-epoxy-painting",
    excerpt: "Heavy-duty epoxy floor coating and dust-free interior office wall painting.",
    content: "## Scope\n\nApplied industrial epoxy floor sealer and 2 coats commercial Nippon acrylic for high-traffic office spaces. Weekend turnaround with zero downtime.",
    type: "portfolio",
    category: "Painting Services",
    tags: "Epoxy painting,Office painting,Indoors and outdoors painting",
    featured: false,
    published: true,
    coverImage: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&auto=format&fit=crop&q=70",
    views: 167,
    whatsappClicks: 31,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-5a", postId: "fallback-post-5", url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=70", kind: "before", position: 0, createdAt: now },
      { id: "img-5b", postId: "fallback-post-5", url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&auto=format&fit=crop&q=70", kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-6",
    title: "Licensed Electrician HDB Full Rewiring & DB Box in Tampines",
    slug: "licensed-electrician-hdb-rewiring-tampines",
    excerpt: "Complete 4-room HDB flat electrical overhaul: EMA-compliant rewiring, 12-way Hager DB box, and RCCB safety testing.",
    content: "## Project Scope\n\n- Complete HDB 4-room flat electrical rewiring adhering strictly to Singapore EMA and SS CP5 electrical standards.\n- Upgraded obsolete fuse unit to a modern Hager 12-way Distribution Board (DB) with dedicated RCCB residual current circuit breakers.\n- Installed 18 new double 13A switch socket outlets, concealed kitchen cooker point, and 14 dimmable architectural LED ceiling points.\n- Completed insulation resistance testing and SP Services connection inspection with zero defects.",
    type: "portfolio",
    category: "Electrical Services",
    tags: "Licensed electrician,Electrical rewiring,DB Box,Tampines,EMA compliant",
    featured: true,
    published: true,
    coverImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=70",
    views: 284,
    whatsappClicks: 65,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-6a", postId: "fallback-post-6", url: "https://images.unsplash.com/photo-1581092446327-9b52bd1570c2?w=1200&auto=format&fit=crop&q=70", kind: "before", position: 0, createdAt: now },
      { id: "img-6b", postId: "fallback-post-6", url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=70", kind: "after", position: 1, createdAt: now },
    ],
  },
  {
    id: "fallback-post-7",
    title: "Emergency Power Trip & Short Circuit Repair in Jurong West",
    slug: "emergency-power-trip-repair-jurong",
    excerpt: "Emergency troubleshooting for a total blackout caused by an underground concealed water heater short circuit. Restored power in 45 minutes.",
    content: "## Issue & Resolution\n\nHomeowner experienced immediate main RCCB tripping whenever switching on the water heater circuit.\n- Deployed diagnostic megohmmeter to trace concealed neutral-earth breakdown in the master bath conduit.\n- Bypassed faulty segment with flame-retardant heat-resistant wiring.\n- Full load stress test conducted and certified safe.",
    type: "portfolio",
    category: "Electrical Services",
    tags: "Power trip,Emergency electrician,Short circuit,Jurong",
    featured: false,
    published: true,
    coverImage: "https://images.unsplash.com/photo-1581092446327-9b52bd1570c2?w=1200&auto=format&fit=crop&q=70",
    views: 198,
    whatsappClicks: 49,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-7a", postId: "fallback-post-7", url: "https://images.unsplash.com/photo-1581092446327-9b52bd1570c2?w=1200&auto=format&fit=crop&q=70", kind: "gallery", position: 0, createdAt: now },
    ],
  },
  {
    id: "fallback-post-8",
    title: "Islandwide Handyman Door Lock, TV Console & Wall Mounting in Woodlands",
    slug: "handyman-door-lock-wall-mounting-woodlands",
    excerpt: "Precision heavy-duty concrete drilling for 75-inch TV swivel bracket, digital smart lock installation, and sliding balcony door roller realignment.",
    content: "## Handyman Scope\n\n- Heavy-duty wall mounting on reinforced concrete shear wall using Fischer DuoPower rawlplugs.\n- Replaced misaligned main door mortise lock with high-security digital smart lock.\n- Repaired stuck sliding aluminum door rollers with heavy-duty stainless steel bearing wheels.",
    type: "portfolio",
    category: "Handyman Services",
    tags: "Handyman Singapore,Door lock repair,TV mounting,Woodlands",
    featured: false,
    published: true,
    coverImage: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=1200&auto=format&fit=crop&q=70",
    views: 154,
    whatsappClicks: 38,
    authorId: null,
    createdAt: now,
    updatedAt: now,
    images: [
      { id: "img-8a", postId: "fallback-post-8", url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=1200&auto=format&fit=crop&q=70", kind: "gallery", position: 0, createdAt: now },
    ],
  },
]

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "fallback-test-1",
    name: "Mrs Tan",
    role: "5-Room HDB Owner · Punggol",
    rating: 5,
    content: "Painted our entire flat in 2.5 days. Edges were crisp, zero paint on our furniture, and he cleaned up thoroughly before leaving. Felt like a brand new flat.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-2",
    name: "Daniel Lim",
    role: "Condo Owner · Serangoon",
    rating: 5,
    content: "Re-did my kitchen. Quote was 100% transparent, no surprises, finished on the exact date promised. The solid-surface countertop seaming was invisible.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-3",
    name: "Priya K",
    role: "BTO Owner · Sengkang",
    rating: 5,
    content: "Built my feature wall and TV console. Came back twice to fine-tune the LED lighting until I was happy. That level of after-service is rare in Singapore.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-4",
    name: "Mr Goh",
    role: "Landed Owner · Bukit Timah",
    rating: 5,
    content: "Full rewire of a 4-storey house. LEW-signed, EMA-compliant, zero snags at handover. Highly recommended trade specialist.",
    avatar: null,
    published: true,
    createdAt: now,
  },
  {
    id: "fallback-test-5",
    name: "Aisha Bte Rahmat",
    role: "EC Owner · Sembawang",
    rating: 5,
    content: "Re-did my master bathroom. He explained the waterproofing process so I understood why it mattered. The walk-in rain shower is incredible.",
    avatar: null,
    published: true,
    createdAt: now,
  },
]
